language: java

jdk:
    - oraclejdk8

env:
    - NODE_VERSION="7.4.0"

matrix:
    include:
        -   os: windows
            language: shell # workaround for https://travis-ci.community/t/java-support-on-windows/286/2
            before_install:
                - choco install --yes elm-platform
                - choco install jdk8
                - ls "/c/Program Files/Java"
                - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"

        -   os: linux
            before_install:
                - nvm install $NODE_VERSION
                - npm install -g elm

        -   os: osx
            osx_image: xcode9.3 # Xcode 9.3 is the last version that supports JDK 8 on Travis
            before_install:
                - npm install -g elm


install:
    - echo Installed elm `elm --version`
    - java -version
    - ./gradlew assemble  --console=plain --no-daemon


script: ./gradlew check --info --console=plain --max-workers=1 --no-daemon


before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/


notifications:
    email: false
